export const registryAbi = [
  {
    type: "function",
    name: "publishRun",
    stateMutability: "nonpayable",
    inputs: [
      { name: "runId", type: "bytes32" },
      {
        name: "supplied",
        type: "tuple",
        components: [
          { name: "evidenceHash", type: "bytes32" },
          { name: "manifestHash", type: "bytes32" },
          { name: "inputHash", type: "bytes32" },
          { name: "normalizedResultHash", type: "bytes32" },
          { name: "sourceRevisionHash", type: "bytes32" },
          { name: "paymentReceiptHash", type: "bytes32" },
          { name: "previousRunId", type: "bytes32" },
          { name: "provider", type: "address" },
          { name: "anchoredBy", type: "address" },
          { name: "anchoredAt", type: "uint40" },
          { name: "gateBitmap", type: "uint16" },
          { name: "status", type: "uint8" },
          { name: "providerSignatureVerified", type: "bool" },
          { name: "isFixture", type: "bool" },
        ],
      },
      { name: "canonicalEvidence", type: "bytes" },
      { name: "providerSignature", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getRun",
    stateMutability: "view",
    inputs: [{ name: "runId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "evidenceHash", type: "bytes32" },
          { name: "manifestHash", type: "bytes32" },
          { name: "inputHash", type: "bytes32" },
          { name: "normalizedResultHash", type: "bytes32" },
          { name: "sourceRevisionHash", type: "bytes32" },
          { name: "paymentReceiptHash", type: "bytes32" },
          { name: "previousRunId", type: "bytes32" },
          { name: "provider", type: "address" },
          { name: "anchoredBy", type: "address" },
          { name: "anchoredAt", type: "uint40" },
          { name: "gateBitmap", type: "uint16" },
          { name: "status", type: "uint8" },
          { name: "providerSignatureVerified", type: "bool" },
          { name: "isFixture", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "event",
    name: "RunPublished",
    anonymous: false,
    inputs: [
      { name: "runId", type: "bytes32", indexed: true },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "manifestHash", type: "bytes32", indexed: false },
      { name: "inputHash", type: "bytes32", indexed: false },
      { name: "normalizedResultHash", type: "bytes32", indexed: false },
      { name: "sourceRevisionHash", type: "bytes32", indexed: false },
      { name: "paymentReceiptHash", type: "bytes32", indexed: false },
      { name: "previousRunId", type: "bytes32", indexed: false },
      { name: "provider", type: "address", indexed: true },
      { name: "anchoredBy", type: "address", indexed: true },
      { name: "anchoredAt", type: "uint40", indexed: false },
      { name: "gateBitmap", type: "uint16", indexed: false },
      { name: "status", type: "uint8", indexed: false },
      { name: "providerSignatureVerified", type: "bool", indexed: false },
      { name: "isFixture", type: "bool", indexed: false },
      { name: "canonicalEvidence", type: "bytes", indexed: false },
    ],
  },
] as const;
